name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: touch .env
    - run: echo DATABASE_URL=${{secrets.DATABASE_URL}} >> .env
    - run: echo TOKEN_SECRET=${{secrets.TOKEN_SECRET}} >> .env
    - run: echo LINODE_OBJECT_STORAGE_BUCKET_NAME=${{secrets.LINODE_OBJECT_STORAGE_BUCKET_NAME}} >> .env
    - run: echo LINODE_OBJECT_STORAGE_REGION=${{secrets.LINODE_OBJECT_STORAGE_REGION}} >> .env
    - run: echo LINODE_OBJECT_STORAGE_ENDPOINT=${{secrets.LINODE_OBJECT_STORAGE_ENDPOINT}} >> .env
    - run: echo LINODE_OBJECT_STORAGE_ACCESS_KEY_ID=${{secrets.LINODE_OBJECT_STORAGE_ACCESS_KEY_ID}} >> .env
    - run: echo LINODE_OBJECT_STORAGE_SECRET_ACCESS_KEY=${{secrets.LINODE_OBJECT_STORAGE_SECRET_ACCESS_KEY}} >> .env
    - run: npm i
    - run: npm run build
    - run: pm2 stop 0 
    - run: pm2 start 0
    - run: pm2 save
    - run: sudo service nginx restart
